### ISSUE TITLE
A tiny fix to allow negative percentage outlineOffsetX/Y values in troika-three-text

### ISSUE THREAD

**Issue by subblue** [protectwise/troika#100]
It is great having the outline blur options now!

One little tweak to the percentage value parsing would allow negative `outlineOffsetX/Y` values [here](https://github.com/protectwise/troika/blob/master/packages/troika-three-text/src/Text.js#L619), useful to get the full range of drop-shadow.

`let match = value.match(/^(-?[\d.]+)%$/)`

**Comment by lojjic** [comment]
Ah, good catch, thank you! We probably only want to allow negatives for these offsets, and not for blur/width where that function is also used.

**Comment by lojjic** [comment]
Fixed, thanks!
