### ISSUE TITLE
"bundling" with vite __name is no defined error in workerBootstrap

### ISSUE THREAD

**Issue by n1ru4l** [protectwise/troika#111]
I am currently trying to migrate from create-react-app over to vote and I am hitting a roadblock with this one:

```
34141245-28a7-4a6e-a323-58891f767907:5 Uncaught ReferenceError: __name is not defined
    at workerBootstrap (34141245-28a7-4a6e-a323-58891f767907:5)
    at 34141245-28a7-4a6e-a323-58891f767907:157
workerBootstrap @ 34141245-28a7-4a6e-a323-58891f767907:5
(anonymous) @ 34141245-28a7-4a6e-a323-58891f767907:157
```

The exact error occurs in this piece of code
```
/** Worker Module Bootstrap: #default **/

;(function workerBootstrap() {
  var modules = Object.create(null);
  var __name2 = /* @__PURE__ */ __name((a) => {
```

I guess this could also just be an issue with vite as it transforms the code, but as the code in WorkerModules is responsible for generating the module code form a text file it might also be possible that this must be addressed within troika-worker-utils

**Comment by n1ru4l** [comment]
I was able to solve it like that.

```
import { defineConfig } from "vite";
import reactRefresh from "@vitejs/plugin-react-refresh";
import macrosPlugin from "vite-plugin-babel-macros";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [reactRefresh(), macrosPlugin()],
  resolve: {
    alias: {
      "socket.io-client": "socket.io-client/dist/socket.io.js",
      domhandler: "node_modules/domutils/node_modules/domhandler/lib/index.js",
    },
  },
  optimizeDeps: {
    exclude: ["troika-worker-utils", "troika-three-utils", "troika-three-text"],
  },
});
```

**Comment by lojjic** [comment]
Glad you found a workaround! That's interesting though. I've run into problems in the past with build tools transpiling worker functions to introduce closure vars which breaks them (e.g. Babel does this for certain ES6 features in external helpers mode). Generally I try to avoid that by keeping transpile-able code out of those functions, but it seems maybe something here is triggering Vite to modify the code anyway? I'll take a look and see if there's anything obvious.

I wonder if there's any sort of hint I can leave (similar to the PURE comment) that could tell it not to touch the code in that function... 🤔

**Comment by n1ru4l** [comment]
yeah vite has some kind of pre bundling to avoid loading too many files (e.g. loading es lodash eould result in loading hundreds of files). since troika already ships prebundles es modules it is safe to omit it from the pre bundle step

**Comment by eldardada** [comment]
I have the same problem. But I am using vue + ts and self worker.

Reference error: __name is not defined. 

var browserWorkerPolyFill = function browserWorkerPolyFill2(workerObj) {
  workerObj.on = workerObj.addEventListener;
  workerObj.off = workerObj.removeEventListener;
  return workerObj;
};
browserWorkerPolyFill(self);

  var commonjsGlobal2 = typeof globalThis !== "undefined" ? globalThis : typeof window !== "undefined" ? window : typeof global !== "undefined" ? global : typeof self !== "undefined" ? self : {};
  function createCommonjsModule(fn, basedir, module) {
    return module = {
      path: basedir,
      exports: {},
      require: /* @__PURE__ */ __name(function require2(path, base) {
        return commonjsRequire(path, base === void 0 || base === null ? module.path : base);
      }, "require")
    }, fn(module, module.exports), module.exports;
  }
  __name(createCommonjsModule, "createCommonjsModule");

**Comment by eldardada** [comment]
macrosPlugin is also needed to solve the problem? I have the same problem with hls.js
