### ISSUE TITLE
Curved UI

### ISSUE THREAD

**Issue by MichaelHazani** [protectwise/troika#114]
Hi! 
I'm wondering what it would take to extend TextMesh to support shapes other than plane - and in particular a curved plane, which not only has that cool sci fi vibe, but is very ergonomic to read in VR in particular.

(Having [lots of fun](https://twitter.com/i/timeline) with your great lib, btw - thank you!)

**Comment by lojjic** [comment]
Glad to hear it! Your link didn't work but I'm curious what you're up to. :)

Have you seen the [curveRadius](https://protectwise.github.io/troika/troika-three-text/#curveradius) parameter?

Other warped planes can be done with custom vertex shaders.

**Comment by MichaelHazani** [comment]
oh my! 
Apologies about the link, [here it is](https://twitter.com/michaelhazani/status/1382098319720189952?s=20) as well as a more recent [update](https://twitter.com/michaelhazani/status/1382439079002972162?s=20) (including curved UI - can't believe I missed it. Then again this little library is so feature-rich!)

This was clearly made by someone who felt the many pain points of text in webgl, then set out to resolve them, one by one. I'm very impressed and grateful.

**Comment by lojjic** [comment]
Amazing! Thank you for sharing.

If you find during your text editing work that any code or gained knowledge could be helpful in https://github.com/protectwise/troika/issues/28, feel free adding it there.

"the many pain points of text in webgl" you really get me 😆
