### ISSUE TITLE
Custom uniforms in DerivedShader

### ISSUE THREAD

**Issue by YuryKonvpalto** [protectwise/troika#115]
Hi Guys!

Could not figure out how to inject a custum uniform into a DerivedShader through 'options'.
Docs are not saying anything precise, just mentioning that there is an option 'uniforms'.

I tried to inject it this way, but it doesnt worked for me:

const customMaterial = createDerivedMaterial(
    baseMaterial,
    {
      timeUniform: 'elapsed',
      uniforms: `qqq`
}

It just adds a uniforms property like this: 

uniforms:
0: "q"
1: "q"
2: "q"

What do I do wrong? How to inject custom uniforms to derivedMaterial and how to assign some value to them?

**Comment by lojjic** [comment]
Apologies for the unclear documentation! I will add some clarification there.

The `uniforms` property here is an object of objects, in the same exact format as Three's `ShaderMaterial`: https://threejs.org/docs/#api/en/materials/ShaderMaterial

**Comment by YuryKonvpalto** [comment]
> 
> 
> Apologies for the unclear documentation! I will add some clarification there.
> 
> The `uniforms` property here is an object of objects, in the same exact format as Three's `ShaderMaterial`: https://threejs.org/docs/#api/en/materials/ShaderMaterial.uniforms


Thanx for promt answer, Lojjic.

I've tried this variant before and it adds a uniforms to custommaterial property:

uniforms:
time2: {value: 0.1}_

But it still doesn't add the uniform to the text of the shader, I can't see it using a console.log:

const customMaterial = createDerivedMaterial(
baseMaterial,
{
timeUniform: 'elapsed',
uniforms: {
    time2: {value: 0.1}
}
customMaterial.onBeforeCompile = function (shader) {
     console.log(shader);
  }

So actual shader when compiled doesn't contains a custom uniform.
When I try to use it in shader it throws error: "'time2' : undeclared identifier".

Could you check please mechanism of assigning custom uniforms on your environment?

Troika itself works otherwise properly (timeUniform and so on..)
I've installed troika with npm (if it makes a difference).

**Comment by lojjic** [comment]
Oh! Yeah you still have to declare the uniforms in your GLSL (vertexDefs and/or fragmentDefs), it doesn't automatically inject them (other than timeUniform which is special in that regard.)

Here's a good example: https://github.com/protectwise/troika/blob/master/packages/troika-three-utils/src/BezierMeshMaterial.js

**Comment by YuryKonvpalto** [comment]
> 
> 
> Oh! Yeah you still have to declare the uniforms in your GLSL (vertexDefs and/or fragmentDefs), it doesn't automatically inject them (other than timeUniform which is special in that regard.)
> 
> Here's a good example: https://github.com/protectwise/troika/blob/master/packages/troika-three-utils/src/BezierMeshMaterial.js

At last it works!:))

You definitely have to mention it somehow in Docs or extend an example of DerivedMaterial in Docs with custom uniform.:)

Thanx again, Lojjic. Very appreciate!
