### ISSUE TITLE
#pragma glslify (noise function)

### ISSUE THREAD

**Issue by YuryKonvpalto** [protectwise/troika#116]
Hy Guys again!

Is it possible to use predefined noises (like this: #pragma glslify: snoise3 = require(glsl-noise/simplex/3d) in derivedShader and if so - where to put it (options?) in order it would work?

I've tried to put it inside vertexDefs, but if I try to reach it in vertexTransform (float noise = snoise3(position);), - an error appears: "'glslify' : unrecognized pragma".

Any suggestions please?

**Comment by lojjic** [comment]
I'm not that familiar with glslify, isn't that something you'd have to set up some sort of build-time transformation pipeline to evaluate those pragmas?

**Comment by YuryKonvpalto** [comment]
> 
> 
> I'm not that familiar with glslify, isn't that something you'd have to set up some sort of build-time transformation pipeline to evaluate those pragmas?

I'm not very familiar with pragmas also, but it works like sort of ES6 module for GLSL, - very convinient. 
This line: "#pragma glslify: snoise3 = require(glsl-noise/simplex/3d)" in upper part of shader imports and inserts into shader somehow the whole simplex3d implementation of Stefan Gustavson simplex noise function.

I found a simple workaround - I will just put the whole Stefan Gustavson simplex noise function into shader with vertexDefs..

But pragma would be more convinient:).

Thanx a lot again, Lojjic!

**Comment by lojjic** [comment]
Yeah, inserting it directly in the string is probably the way to go. Those glslify pragmas don't just work automatically, you have to have something in your build process that performs that transformation. If you had that set up, I'm guessing it would work.
