### ISSUE TITLE
Fix transitive peerDependencies for 'three'

### ISSUE THREAD

**Issue by lojjic** [protectwise/troika#123]
Right now we define the three.js version range once in troika-three-utils's peerDependencies, and it was my assumption that the other packages which depend on that would "inherit" that peer dependency. It turns out that's not really how it works, and this can confuse tools.

It means redundancy, but each package that directly imports from `three` should declare it in their own peerDependencies.

An upside is that this would allow individual packages to support slightly different version ranges; for example troika-three-text could support a very wide range but troika-xr could narrow itself to a more recent range.

**Comment by n1ru4l** [comment]
@lojjic Is it possible to bump the three dependency from 0.127.0 to 0.128.0 for troika-three-text? This is pretty annoying when working with npm as there is currently no way of enforcing a specific version :(

**Comment by lojjic** [comment]
That's odd, my understanding was that since the version range is defined via `peerDependencies` rather than `dependencies`, it would use whatever actual version you defined in your app, though it would show a warning. I guess you're saying that's not the case? That it actually installs a specific version from the peerDependencies?

If so, I definitely need to rethink the range, maybe do a `>=` like you suggested in #127. I'd have to find a different way to declare/document which versions have been specifically tested as working.

**Comment by lojjic** [comment]
Done in v0.42.0, along with making three's version range open-ended.

This seems to have fixed using troika-three-text from skypack, for instance.
