### ISSUE TITLE
[troika-three-text] Offline/pre-generated SDF texture + glpyh data

### ISSUE THREAD

**Issue by ashthornton** [protectwise/troika#132]
I've had a quick glance over the source code but before I go any deeper and potentially make my own fork, I was wondering if there is already a way to provide my own SDF texture + glyph data (thinking a JSON object similar to how other packages handle it?), rather than force the browser to create the same textures and data every time a site is loaded?

I love the fact that it just dynamically works out what it needs based on the input but the initial generation time is quite significant and increases the load time dramatically. I'm essentially using the preload function to generate two SDF fonts with a preset list of characters on site load, then revealing once complete. But in my case, I would rather send in my pre-generated data since I know what will be needed every time, avoiding the generation time.

Amazing work by the way! This is by far the most intuitive and feature-rich package for dealing with SDF text in Three :)

**Comment by lojjic** [comment]
Thanks for bringing this up! There's not currently any support for this, but it's something I've given a good amount of thought to already. 

In my mind this would take the form of adding the ability to serialize a glyph atlas into a form that could then be read back in later. My initial use case there was to serialize the atlas data into localStorage or similar as a cache so SDF generation could be skipped after the first time, but I don't see any reason that same serialized data couldn't also be served up from the network.

I don't think this data would include anything other than the SDF texture(s) and a mapping of glyph ids to atlas position. Other packages also embed some text layout information but I think we'd still want to utilize the actual font file for that.

Things that would need to happen for this to work:

- The glyph atlas would need to maintain a mapping of glyph id to position in the atlas. Right now the position in the atlas is based purely on order in which each glyph is first encountered in the text, which isn't consistent and wouldn't work when persisting.
- The shader and the attributes it receives would have to be aware of that glyph id-to-position mapping.
- Perhaps not totally necessary, but I think the refactor in #119 would make this easier.

Also maybe related: I have a work-in-progress that performs the [SDF generation utilizing the GPU](https://codesandbox.io/s/wizardly-leftpad-32iqo?file=/test/index.js), which will make that process _much_ faster. That may affect when, or whether, pre-generation is necessary.

**Comment by swingingtom** [comment]
Hi ! Im currently having the same wish.

Im pretty new to this library, so the following questions might sounds silly. 

- What was the main use case/need when choosing this strategy ? Is it still accurate ? What am I missing by trying to avoid this behaviour ?
- Would it rather be a option/plugin/utils instead as being the core feature?  

And Im also agreed with @ashthornton about its statement

> Amazing work by the way! This is by far the most intuitive and feature-rich package for dealing with SDF text in Three :)
👍

**Comment by lojjic** [comment]
I've given this more thought from time to time, and I think I've convinced myself that since glyph SDF generation is now much faster due to GPU acceleration, the request to support offline pre-generation probably wouldn't be worth the effort. I'm going to close this, but please feel free to continue discussion if you disagree with my assessment!
