### ISSUE TITLE
Having to move camera for all text to render

### ISSUE THREAD

**Issue by FRMR1** [protectwise/troika#138]
I'm having an issue with troika-three-text where some of the text doesn't render until I move the camera. I'm using Three.js and React Three Fiber and am preloading all of the fonts and glyphs, and the callbacks are firing successfully. I can sit for as long as possible and some of the text won't render until I move the camera. I know this is a pretty general explanation but I'm just wondering if this is a known issue or if there is a known fix of why some text would be rendering initially and why some text needs camera movement before it renders.

**Comment by lojjic** [comment]
@FRMR1 Are you using the `Text` component from `drei`, or your own wrapper?

If you're using `drei`'s, then it should already be handling this. If it's your own, then you need to make sure that you trigger a render (`invalidate` in r3f IIRC) [after the text's sync completes](https://protectwise.github.io/troika/troika-three-text/#handling-asynchronous-updates).

**Comment by FRMR1** [comment]
Yes that was the problem, thank you. I've switch to the drei wrapper and now the text is rendering almost immediately. I'm still getting some text that doesn't render which is close to the edge of the clip space though and requires moving the camera so the text is closer to the center of the screen. I'm assuming it detects if the text bounding box is on screen but it doesn't seem to be matched up exactly right with my camera's fov. Is there any way to adjust or sync that?

**Comment by lojjic** [comment]
Hmmm, that sounds like a bug. Would you be able to put together a codesandbox or similar showing that edge of viewport behavior?

**Comment by lojjic** [comment]
Closing this for now. @FRMR1 feel free to reopen if you can provide a testcase showing the viewport edge / FOV issue you mentioned. Thanks!
