### ISSUE TITLE
Cannot use troika-three-text in SvelteKit (Vite based)

### ISSUE THREAD

**Issue by FunMiles** [protectwise/troika#139]
I am moving an app from Svelte with webpack to SvelteKit and it works in development mode. However when building the release code, this import fails:
```js
import {Text} from "troika-three-text";
```
with the following error message:
```
> The requested module 'troika-three-text' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'troika-three-text';
const {Text} = pkg;
file:///Users/michel/Development/App/.svelte-kit/output/server/chunks/World-38d02b6b.js:17
import {Text} from "troika-three-text";
        ^^^^
```
After trying the proposed fix, the problem changes to:
```js
'default' is not exported by node_modules/troika-three-text/dist/troika-three-text.esm.js, imported by src/lib/Components/ThreeD/Text.svelte
file: /Users/michel/Development/App/src/lib/Components/ThreeD/Text.svelte:9:11
 7:     import * as THREE from 'three';
 8:     import { key } from './threeDViewTag';
 9:     import troika from 'troika-three-text'; 
```

It seems that the fix might be to have troika-three-text create a default export containing all the single exports.

Would that be possible with little changes? (I am far from understanding all the ins and outs of imports CommonJS vs ES6 etc...)

Edit: I went manually in the file `troika-three-text.esm.js` and added 
```js
export default { GlyphsGeometry, Text, configureTextBuilder, createTextDerivedMaterial, dumpSDFTextures, fontProcessorWorkerModule, getCaretAtPoint, getSelectionRects, preloadFont };
```
and it seems to take it.
It's a workaround and it would be nice to have it by default.

Edit 2: using 
```js
import * as troika from 'troika-three-text'; 
const { Text } = troika;
```
works.  It's a more elegant workaround.

**Comment by lojjic** [comment]
Cool, I was going to ask if maybe `import * as` would work, so I'm glad you found it does. :)

Out of curiosity, what version of Node are you running? While searching around about this error message I saw some indication that maybe Node versions after 14.13 added support for named CJS exports?

**Comment by FunMiles** [comment]
@lojjic I am running v16.4.0. I am battling many issues with svelte-kit. I guess it is fresh technology not fully mature yet.
Right now, I am trying to load workers that import external packages and it is not working at all in the build phase or in dev mode under Safari or Firefox. Yet troika-three-text uses such a worker, but it is compiled/packaged separately. Maybe I'm going to have to take that approach. It is sad though.
