### ISSUE TITLE
multi-line text not centering properly

### ISSUE THREAD

**Issue by peterqliu** [protectwise/troika#147]
`t.anchorX = 'center'` works well for single-line labels, and for multiple lines, it does align the text to the center of its bounding box. However, the text on each line is no longer horizontally centered:

<img width="124" alt="Screen Shot 2021-08-09 at 3 48 21 PM" src="https://user-images.githubusercontent.com/4551508/128785314-2e95a377-a311-4afa-9725-d07f4a87d359.png">
^ each line's text is left aligned, though the whole mesh is properly positioned to the center of the text block's imaginary bounding box

**Comment by peterqliu** [comment]
(Line breaks were achieved with a finite `t.maxWidth` value, but `whiteSpace` and `overflowWrap` were left to defaults)

**Comment by lojjic** [comment]
I think you want [textAlign](https://protectwise.github.io/troika/troika-three-text/#textalign) = 'center'?

**Comment by peterqliu** [comment]
thanks, that's it!
