### ISSUE TITLE
I'd like a width property that is like a textbox width for alignment purposes

### ISSUE THREAD

**Issue by bzuillsmith** [protectwise/troika#160]
I'm attempting to use troika-three-text to draw multiline text entities of CAD files. I want to give it a specific textbox width for alignment purposes.

Say the maxWidth is 100, the alignment is center, and the maximum that any line actually covers is 50. Currently, the text produced by troika-three-text is centered as if the "text box" is 50 wide, not 100 wide. Thus it is shifted to the left of it's intended position.

It seems like this might be an easy thing to do. This [line of code](https://github.com/protectwise/troika/blob/c2bf886f280ca1c587bc3ae80a41d30ce8cb6dce/packages/troika-three-text/src/worker/Typesetter.js#L291) uses maxLineWidth which is the longest line of text (not the explicitly set maxWidth). I propose we add a `width` field to the options that effectively forced maxLineWidth to the given value.

**Comment by lojjic** [comment]
Thanks for the suggestion. I think you use case can be handled with a combination of `anchorX = 'center'` and `position.x = halfTheMaxWidth` ...?

**Comment by bzuillsmith** [comment]
Yeah, I just figured that out last night. I check if it should be center or right aligned and adjust accordingly with position.x. I was a little concerned that the text was asynchronously figured because we don't do anything on a render loop; so I thought maybe there would not be enough time to get the bounding boxes and do the math. But the sync callback seem to run in time for me so far.

**Comment by lojjic** [comment]
Cool! I'm not sure why you need to do math with the bounding box though, maybe I'm not understanding your problem fully?

**Comment by bzuillsmith** [comment]
oh, maybe you were suggesting how to integrate the code into troika-three-text?  It sounded to me like you were giving me a way to do it without changing this lib. That or I'm missing something which could totally be the case. I didn't see anything exposing the actual width of the text to consumers of the library so my code currently gets the bounding box.

If you're talking about how to adjust things within the troika code -- that would work, but might be a breaking change unless you add another property to indicate if the extra offset is desired.

**Comment by bzuillsmith** [comment]
ah, perhaps... this is for rendering CAD files. I'm using it for the case of multiline text entities. In CAD, the anchor point is actually still top-left most of the time, but it can change. And independent of the anchor, a width and text alignment is used to position the text. I guess I hadn't thought about changing the anchor point for text alignment purposes since I was still thinking of how CAD does it. I'll see if that works better for me than the bounding box. But ultimately I'll still need some kind of extra offset with that approach

**Comment by lojjic** [comment]
OK, if you run into issues let me know and I'll think how to improve it for you.

But I do think that with your original example of a "textbox" with a fixed width of 100, this should give equivalent behavior without having to measure the text bounds:

```
const textBoxWidth = 100
text.maxWidth = textBoxWidth
text.anchorX = 'center'
text.position.x = xPosFromCAD + textBoxWidth / 2
```

You can just think of `anchorX` as what horizontal position in the text you want to remain _stable_. If you're center-aligning text in a fixed-width box, you want that point to be the text's center. And then you just position that anchor point at the fixed-width box's centerpoint.

**Comment by bzuillsmith** [comment]
Got it, makes sense. It definitely sounds like this will work to get the position without a sync callback and bounding box. The only downside I can think of is that the position won't reflect the original CAD anchor point anymore, but it's probably not a big deal. Currently what I'm working on is only a viewer, though some people have been forking it to make it interactive and add features.
