### ISSUE TITLE
getting attempted import error on terminateWorker

### ISSUE THREAD

**Issue by ghost** [protectwise/troika#162]
./node_modules/troika-three-text/dist/troika-three-text.esm.js
Attempted import error: 'terminateWorker' is not exported from 'troika-worker-utils'.

I can see it is exported from 'troika-worker-utils'. Not sure why this is firing. Trying to recreate this example in my r3f project.

https://codesandbox.io/embed/troika-3d-text-via-react-three-fiber-ntfx2?fontsize=14

**Comment by lojjic** [comment]
Closing; reopen it if you can provide details. Thanks!
