### ISSUE TITLE
[InstancedUniformsMesh] a way to undo .setUniformAt

### ISSUE THREAD

**Issue by peterqliu** [protectwise/troika#163]
First off, this is such a great extension of InstancedMesh to empower different properties per instance. I was wondering, though, if there's a graceful way to reset a certain uniform back to use the default `material.uniforms` for all instances, after it was initially invoked with `.setUniformAt`

In the interest of minimizing memory overhead, I'd like to be able to use `setUniformAt` for properties that need to vary between instances, the material-wide uniforms for props that don't vary, and to switch a prop between the two situations gracefully.

**Comment by lojjic** [comment]
I've added an `unsetUniform(name)` method in version 0.44.0 - [docs](https://protectwise.github.io/troika/three-instanced-uniforms-mesh/#resetting-to-defaults). Let me know if this doesn't work for you. Thanks!

**Comment by peterqliu** [comment]
@lojjic that's perfect, thanks!
