### ISSUE TITLE
[troika-three-text] Bad caret positions if last chars: 'fl'

### ISSUE THREAD

**Issue by MetaHegemon** [protectwise/troika#165]
Hello! If last chars of text is 'fl' then last caretPositions is zero. 
Look up console of this example: https://codesandbox.io/s/troika-three-text-caretpositions-error-wielp 

Cheked in 0.43.1-alpha.0

**Comment by lojjic** [comment]
Good find! That 'fl' is a ligature so it's a single glyph spanning two characters. In most cases the same caretPosition will be copied to both characters, but there's a bug that doesn't do that copying when it's the final glyph. Should be an easy fix. :)

**Comment by lojjic** [comment]
This has been fixed in version `0.44.0`. Thanks for the report!
