### ISSUE TITLE
Font rendering unprecise

### ISSUE THREAD

**Issue by fabianhijlkema** [protectwise/troika#167]
Using the troika-three-text package I was rendering text in my Three.js project, which works almost perfectly. I did see that the particular font I use renders very unprecise or glitchy when zoomed in very closely. In my use-case the text will be displayed very large, so this is visible. I'll provide a screenshot of the rendering using troika-three-text and the same glyph in InDesign.

Is there any way to render the font more precise, like the original font? The issue might arise due to the specific design of this particular typeface, which has no curves anywhere, but consists of straight lines.

Correct rendering in Indesign (this font has no curves by design)
<img width="1044" alt="Screenshot 2021-11-25 at 21 10 15" src="https://user-images.githubusercontent.com/2919995/143496475-d08b74c0-26b5-48f4-af03-a105ca27e122.png">

Incorrect rendering with troika-three-text
<img width="659" alt="Screenshot 2021-11-25 at 21 10 41" src="https://user-images.githubusercontent.com/2919995/143496482-2e68ac91-307a-43f2-ae26-e81a3be5ba67.png">

**Comment by lojjic** [comment]
Hi, yes unfortunately these imprecisions are a downside of the single-channel SDF approach that's currently used, particularly the rounding off of corners - you trade off precision for a lot of speed and efficiency.

You can increase the precision by increasing the size of the SDF textures that it creates for each glyph using the [sdfGlyphSize config property](https://protectwise.github.io/troika/troika-three-text/#sdfglyphsize) - by default it's 64, you could try bumping that up to 128 or even 256 but be aware it will also increase processing time and memory usage.

**Comment by fabianhijlkema** [comment]
Hi, sorry that I missed that property while looking for a solution. It indeed improves a little when I bump it up, but it is a trade-off as you mentioned. But at least I know the origin of the 'issue'. Thanks you!
