### ISSUE TITLE
[Question] using noto Sans for Chinese Japanese Characters?

### ISSUE THREAD

**Issue by arpu** [protectwise/troika#17]
Hi,

would it be possible to use notoSans for this Characters? 
 i tryed https://google-webfonts-helper.herokuapp.com/fonts/noto-sans?subsets=cyrillic,vietnamese,latin

woff  but cannot see any character only latin

**Comment by lojjic** [comment]
Non-Latin characters should work if they're included in the font file, yes, though it won't do any advanced layout (left-to-right only).

Cyrillic and Vietnamese seem to work fine for me using that .woff file you linked to:

![image](https://user-images.githubusercontent.com/138124/68613158-63330d00-047b-11ea-9829-0f452ef3dd4d.png)
![image](https://user-images.githubusercontent.com/138124/68613305-a9886c00-047b-11ea-90c2-e64af60b2c5b.png)

**Comment by arpu** [comment]
ohh thx looks like i use wrong characters for the testing

**Comment by arpu** [comment]
ok i see
the japanese is different woff https://google-webfonts-helper.herokuapp.com/fonts/noto-sans-jp?subsets=japanese

so would it be possible to use more  woff files?

**Comment by arpu** [comment]
would be cool to have some thing for Latin Chinese Japanese Cyrillic and Vietnamese

**Comment by lojjic** [comment]
Sorry I'm not sure what you're asking... does that Japanese woff not work?

**Comment by arpu** [comment]
yes it works but i  can only use one woff  or is there a way to combining the Japanese woff and the latin, Cyrillic  woff?

**Comment by lojjic** [comment]
Oh I see, so you want to be able to specify a list of font files and have it pick individual characters from whichever of those files contains them? That seems like a reasonable feature, but not supported at the moment.

In the meantime I would imagine you could create a combined font file with existing font editor tools.

**Comment by lojjic** [comment]
That sounds a bit like https://github.com/protectwise/troika/issues/13 if I'm understanding you correctly?

**Comment by arpu** [comment]
ah yeaah exactly!
