### ISSUE TITLE
Invisible plane-like mesh added by troika-three-text library

### ISSUE THREAD

**Issue by LR17** [protectwise/troika#170]
Hello,
is it possible that troike-three-text adds an invisible mesh to the scene? it is not visible by the default camera but it is by SSAO postprocessing effect.

**Comment by lojjic** [comment]
You're likely seeing the plane geometry it uses for the text, without its custom vertex shader that turns that plane into a bunch of text glyphs. Postprocessing pipelines sometimes use a scene-wide "override material" which prevents any custom shader materials from being applied. If you're using the `postprocessing` npm package specifically then there is a [workaround described in the docs](https://protectwise.github.io/troika/troika-three-text/#postprocessing).

**Comment by LR17** [comment]
Oh, I see. Thank you
