### ISSUE TITLE
[Question] get the geometry.visibleGlyphs and geometry.visibleGlyphs.length

### ISSUE THREAD

**Issue by arpu** [protectwise/troika#19]
Hi,
it looks like in aframe text its possible to get this data
what i try is to port aframe-material input to troika-text 

https://github.com/etiennepinchon/aframe-material/blob/master/src/input/index.js#L180

**Comment by lojjic** [comment]
Can you give me details about what info exactly you need? There may be existing ways to get it.

**Comment by arpu** [comment]
i am not sure, but i think its the glyphs visible width

**Comment by lojjic** [comment]
If it's just the total width of the text block you need, that's currently available in a private `_textRenderInfo` property - something like:

```
let totalWidth = 0
const textInfo = textMesh._textRenderInfo
if (textInfo) { //NOTE: may be null before async processing completes
  totalWidth = textInfo.totalBlockSize[0]
}
```

Just be aware that since it's a private property it's not guaranteed to stay the same in the future. I'm open to exposing a public getter for it.

**Comment by arpu** [comment]
yeah thx  a lot this works for now!
