### ISSUE TITLE
Update to latest Three

### ISSUE THREAD

**Issue by lojjic** [protectwise/troika#192]
The examples package is currently locked on an older Three release, which is causing bugs like #188 to go unnoticed. Need to update to the latest Three and resolve the issues that causes.

**Comment by viridia** [comment]
I recently updated my app to the latest three.js and now I am seeing warning messages like this coming from Troika text:

```
THREE.PlaneBufferGeometry has been renamed to THREE.PlaneGeometry.
```

**Comment by lojjic** [comment]
Ahhh, the great de-Buffer-ing has finally happened. Yep, ok. I'll have to see how other libraries are handling this when supporting multiple Three versions.

**Comment by JarvisPrestidge** [comment]
@lojjic Just in case this issue gets forgotten about 👋 it's a real pain to see these warnings everywhere 🙇
