### ISSUE TITLE
Kerning is applied two times

### ISSUE THREAD

**Issue by TimmyTommy** [protectwise/troika#196]
Hello,

Thank you for this amazing library!

Unfortunately I found a bug with the kerning of texts. 
It's probably a bug in the Typr.js/Typr.ts version you are using.
In FontParser.js the line with Typr.U.getPairAdjustment returns the double amount of kerning offset.

I changed 
`glyphX += Typr.U.getPairAdjustment(typrFont, prevGlyphIndex, glyphIndex) * fontScale`
to
`glyphX += Typr.U.getPairAdjustment(typrFont, prevGlyphIndex, glyphIndex) / 2 * fontScale`
which fixed the Problem.

https://github.com/protectwise/troika/blob/bf68d74c6a55449567fba8a610844c102a7e930a/packages/troika-three-text/src/FontParser.js#L223

Here is a screenshot of before and after. The top one is wrong. The 'T' and the 'e' should not be that close to each other.
The font I used is Calibri.

![image](https://user-images.githubusercontent.com/11164463/157755520-effd927d-82b0-47f5-be27-4b6814f43675.png)

**Comment by lojjic** [comment]
Interesting. Is it always exactly doubled from what it should be?

Here's what Typr does: https://github.com/fredli74/Typr.ts/blob/master/src/Typr.U.js#L153

If we can identify it as a bug there then I'd much prefer to have it fixed upstream.

**Comment by TimmyTommy** [comment]
It seems like this change broke it.

https://github.com/fredli74/Typr.ts/commit/a9f3fe3a2e55c01aeae28ac0ef1ac3e848478b7f

@fredli74 sums the 'GPOS' offset and the 'kern' offset. 

I don't have that much know how about font files, 
but it seems like getPairAdjustment should only use either the 'GPOS' data or the 'kern' data and not both at the same time.

https://docs.microsoft.com/en-us/typography/opentype/spec/gpos
https://docs.microsoft.com/en-us/typography/opentype/spec/kern

**Comment by lojjic** [comment]
> It seems like this change broke it.

Hmm, I'm not sure that explains it -- the copy of Calibri.ttf I found doesn't appear to contain any `kern` tagged data in the `GPOS` table, so I don't think that upper loop would be contributing anything there ...? Unless your copy of the font has both.

**Comment by lojjic** [comment]
OK, nevermind, I see now that it does have a GPOS table with kern features in it, I'm not sure why that wasn't showing up in the tool I was using before. I wonder why this font includes both, that seems very inefficient?

Anyway, it seems like an easy fix to only use one and ignore the other. Would you be up for submitting a PR to fredli74's repo?

**Comment by lojjic** [comment]
@TimmyTommy I've released 0.46.3 with the updated Typr, can you please verify and close? Thanks!

**Comment by TimmyTommy** [comment]
Looks good! Thank you very much.

![image](https://user-images.githubusercontent.com/11164463/158024751-185f90b6-3099-4746-a367-c6d2d812f93c.png)
