### ISSUE TITLE
Provide font fallback system

### ISSUE THREAD

**Issue by dronus** [protectwise/troika#206]
When setting texts in HTML / DOM all browsers seem to do everything they can to make every character show up. This also involves switching fonts, if emoticons or foreign language characters are not provided by the currently selected font. 
It is almost impossible for the author to care for all languages that may be used, and the fonts needed, so the system need to handle this.

**Comment by lojjic** [comment]
Totally agree! In fact this work is already in progress, see this branch: https://github.com/protectwise/troika/compare/unicode-ranges
