### ISSUE TITLE
DerivedShader compile error

### ISSUE THREAD

**Issue by alexander-macleod** [protectwise/troika#212]
`THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false Program Info Log: Vertex shader is not compiled. � 
VERTEX ERROR: 0:286: 'float' : syntax error � 
281:       uniform vec2 mouse; 
282: 
283: void troikaVertexTransform1(inout vec3 position, inout vec3 normal, inout vec2 uv) {
284: 
285:           float waveAmplitude = 0.1 
286:           float waveX = uv.x * PI * 4.0 - mod(elapsed / 300.0, PI2); 
287:           float waveZ = sin(waveX) * waveAmplitude; 
288:           normal.xyz = normalize(vec3(-cos(waveX) * waveAmplitude, 0.0, 1.0)); 
289:           position.z += waveZ; 
290: 
291: } 
292:`

the above happens when I try to run the following code from your manual page (the imports etc are fine and the "options.uniforms ... are correctly formatted:

`var base = new THREE.MeshStandardMaterial({
    blending:options.materials.meshShaderMaterial.blending,
    color:options.materials.meshShaderMaterial.color
  });
  if(options.materials.meshShaderMaterial.derrived){
    meshShaderMaterial = createDerivedMaterial(
      base,
      {
        uniforms: {
          elapsed:{value:options.uniforms.time.value},
          mouse:{value:options.uniforms.mouse.value}
        },
        vertexDefs: `
      uniform float elapsed;
      uniform vec2 mouse;
      `,
        // Add GLSL to tweak the vertex... notice this modifies the `position`
        // and `normal` attributes, which is normally not possible!
        vertexTransform: `
          float waveAmplitude = 0.1
          float waveX = uv.x * PI * 4.0 - mod(elapsed / 300.0, PI2);
          float waveZ = sin(waveX) * waveAmplitude;
          normal.xyz = normalize(vec3(-cos(waveX) * waveAmplitude, 0.0, 1.0));
          position.z += waveZ;
        `
      }
    );
  }
  else{
    meshShaderMaterial = base;
  }`

sorry about the formatting above, because of the actual glsl injection I can't seem to format this post correctly
any help would be very much appreciated!

**Comment by alexander-macleod** [comment]
so the semicolon was missing after: float waveAmplitude = 0.1; <-- this

you might want to update the docs in case there are others like with the same issue

**Comment by DmitriyGolub** [comment]
have the same error!

**Comment by lojjic** [comment]
Thanks, I've fixed the error in the docs sample code.
