### ISSUE TITLE
Allow `troika-three-text` to work with bundle tree-shaking

### ISSUE THREAD

**Issue by hamzakubba** [protectwise/troika#215]
Hello, I'm using the `@react-three/drei` library, which includes `troika-three-text` to power its Text component. The problem is, even when not using the Text component, `troika-three-text` currently ends up taking 71.6KB of space (after gzipping) in my production bundle.

I believe the reason this happens is because of the IIFE here:
https://github.com/protectwise/troika/blob/c6a10ae30837d26505d5614b8e15ab49f2ad4625/packages/troika-three-text/src/Text.js#L774

If the initialization logic is moved to the constructor, or is otherwise made lazily invoked, I believe this would fix the issue.

Thanks!

**Comment by lojjic** [comment]
Those IIFEs are marked with the `/*#__PURE__*/` annotation, which is supposed to tell bundlers/minifiers that it contains no side-effects and therefore can be pruned if the result is not used. At the time that [I added those annotations](https://github.com/protectwise/troika/commit/8e76b5c31a3cbda86595654ba9d66d8d635e44a1) they did result in proper tree shake in my testing.

Are you certain that IIFE is the issue? What bundler/minifier are you using?

**Comment by lojjic** [comment]
Also note I will probably not be able to fix this myself in the near term, but I will accept a PR for it if you figure it out.

**Comment by hamzakubba** [comment]
Thanks for the quick response! It's just a basic create-react-app setup (not even using craco or anything). I'm on the latest versions of all the libraries involved in my latest test (initially tested with some versions a couple of weeks old).

I'm not certain that IIFE is the issue. Potentially the `/*#__PURE__*/` only works in first-order dependencies, but second-order ones need something more? It's possible that the drei version needs a pure annotation as well? It seems both this library and drei have `sideEffects: false` in package.json as well as they should. This could also be a webpack 5 change, though the docs still recommend the 'pure' solution now.
