### ISSUE TITLE
RangeError on build step

### ISSUE THREAD

**Issue by Hooman-studio** [protectwise/troika#220]
I get the follow errors on production (I am using next.js) when I run `next build`:

```
Failure loading font http://localhost:3000/models/digital-7-mono.ttf; trying fallback RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint16 (<anonymous>)
    etc...

Failure loading font https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxM.woff RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint16 (<anonymous>)
    etc...
```

When running `next dev` this error doesn't come up.

-I am using troika-three-text via the drei <Text /> component. I found out this uses the `preloadFont` function as well, I am not sure that that is relevant, but just in case it is.

-Error happens both in Chrome and Safari.

**Comment by lojjic** [comment]
Do you have somewhere showing this bug in action that I could look at?

**Comment by lojjic** [comment]
Hmmm, I don't get that error when setting `swcMinify: true` and running that command in your stackblitz. Are there any additional steps needed?

**Comment by lojjic** [comment]
Great! I'm going to close this issue then. 🎉
