### ISSUE TITLE
fillOpacity is not working when using outlineWidth

### ISSUE THREAD

**Issue by flaaudwls** [protectwise/troika#222]
I use troika-three-text in threejs and I found that the fillOpacity 0 can't make the text transparent when we use outlineWidth & outlineColor. Looks like Text3DFacade is working with this in the demo (TextExample.jsx) but troika-three-text is not working.
Please let me know what could be the solution.

**Comment by lojjic** [comment]
Interesting. Can you provide a demo of it failing? Text3DFacade is just troika-three-text underneath so there shouldn't be a difference.

**Comment by lojjic** [comment]
Oh, actually the way `outlineWidth` works it's more like a drop shadow where it's not just an outline it also fills in the glyph interiors. So making the text transparent would just show through to the solid shadow. `strokeWidth` may be more what you're looking for?

**Comment by flaaudwls** [comment]
Interestingly, in this example,  https://troika-examples.netlify.app/#text, I was able to make the transparent outline effect.
Now, I can't create anymore. StrokeWidth makes the transparent texts but that definitely looks different from transparent outline effect.

fillOpacity[¶](https://protectwise.github.io/troika/troika-three-text/#fillopacity)
Controls the opacity of just the glyph's fill area, separate from any configured strokeOpacity, outlineOpacity, and the material's opacity. A fillOpacity of 0 will make the fill invisible, leaving just the stroke and/or outline.

This is coming from the troika doc.
