### ISSUE TITLE
Visual Flickering Bug

### ISSUE THREAD

**Issue by alex-shortt** [protectwise/troika#226]
I've been seeing this issue a lot where text will flicker if you look up past a certain point. It happens with/without outlines, so it's not that. I've tried a few different things but haven't found the pattern, nor have I been able to reproduce it unfortunately ([supposed reproduction](https://codesandbox.io/s/confident-jasper-dmjdhr?file=/src/App.tsx)).

Any ideas on what could be going on? Would be happy to run some tests to get to the bottom of it

https://user-images.githubusercontent.com/6149034/202159432-a4129444-d40b-4d72-a635-608f85e7531f.mp4

**Comment by lojjic** [comment]
This looks similar to behavior I've seen before where the rendering order between the text and the background plane changes. To get proper antialiasing you need the text to always render after the plane. If you give the Text a high `renderOrder` does that affect it?

**Comment by alex-shortt** [comment]
ah yep that was exactly it! amazing

is this something to do with the derived material? it seems to be happening even when the plane behind is placed pretty far away from the text.

**Comment by lojjic** [comment]
No it's a general issue with transparency in webgl being dependent on render order. And ThreeJS's default render order sorting being based on distance to each object's origin in worldspace rather than individual fragment distance.
