### ISSUE TITLE
Orientation

### ISSUE THREAD

**Issue by 007-T** [protectwise/troika#227]
I am trying to change the text orientation and the orientation attribute only lets you set it to the six main planes and even then I cannot have it be diagonal.

My suggestion is to take in two directional vectors that are not multiples of each other and let that define both the plane and the direction of the text.

**Comment by lojjic** [comment]
Is your use case not satisfied by the normal Three.js `rotation` or `quaternion` properties?

The `orientation` property was really a special hack to allow easier importing from tools (like Blender) that assume text is laid out on a different plane, and not for general rotation.

**Comment by 007-T** [comment]
That is correct! Thanks for the help
