### ISSUE TITLE
WARNING: Multiple instances of Three.js being imported.

### ISSUE THREAD

**Issue by pl7y** [protectwise/troika#231]
After installing `https://www.npmjs.com/package/troika-three-text` in a `threejs` app and importing it using `import {Text} from 'troika-three-text'` I get the following warning in console:
```sh
WARNING: Multiple instances of Three.js being imported.
Us @ three.cjs:32260
(anonymous) @ troika-three-text.umd.js:2
(anonymous) @ troika-three-text.umd.js:2
(anonymous) @ graphverse.min.js:1
(anonymous) @ graphverse.min.js:1
```

and rollup claims as well that I am importing two different libraries from the same `three` installation (`three.module.js` and `three.cjs`):
```sh
[BABEL] Note: The code generator has deoptimised the styling of /Users/.../Projects/graphverse/node_modules/three/build/three.module.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/.../Projects/graphverse/node_modules/three/build/three.cjs as it exceeds the max of 500KB.
```
So I guess that the way in which I am importing `threejs` (that is, `import * as THREE from "three";`) is different from the way in which `troika-three-text` imports `threejs`, as they target different files (distributions) of the same library.

What is going on? Is there any way to fix this or work it around?

p.s. The issue is related to #123 but not quite the same.

**Comment by lojjic** [comment]
Did you figure this one out? It's hard to know why, but it looks like your bundler is preferring to resolve to the .umd file rather than the .esm module. If you could configure it resolve to the module, it should then line up with your use of `three.module.js`.

**Comment by pl7y** [comment]
Thanks for the reply, I am no more working with three.js and cannot test the solution; the issue can be closed.
