### ISSUE TITLE
I need to support both Chinese and English, is this library pointless for me?

### ISSUE THREAD

**Issue by tommhuth** [protectwise/troika#237]
Since Chinese seems to disable the layout engine, how could I use this library while stil getting reasonable layout?  I also noticed that including a font with Chinese glyph support is quite a massive download ([NotoSans](https://fonts.google.com/noto/specimen/Noto+Sans+SC) is 8 mb!). Should I skip this library and instead use something custom/homemade?

**Comment by lojjic** [comment]
The next release will include built-in support for Chinese glyphs. It will rely on Noto Sans, though. Probably the full 8MB file at first, though further optimization with unicode range subsets should be possible.

**Comment by tommhuth** [comment]
A 8 mb download seems like an impossible ask for users, so subsetting seems important. 

For anyone else having the same issue, I managed to generate a subset of NotoSans SC [using this Gist](https://gist.github.com/Ashung/7cbed68bdaab918fd01ff73ea1c2ab75) and `opentype.js` 

```js
const opentype = require("opentype.js")
const fs = require("fs")

const fonts = ["assets/fonts/NotoSansSC-Regular.otf"]
const texts = "adfvøæ123以市场洞察为导向的商业模式与解决方案"  
const glyphs = [...new Set(texts.split(""))].join("")

fonts.forEach(item => {
    const font = opentype.loadSync(item)
    const postScriptName = font.getEnglishName("postScriptName") 
    const [familyName, styleName] = postScriptName.split("-") 
    const notdefGlyph = font.glyphs.get(0)

    notdefGlyph.name = ".notdef"

    const subGlyphs = [notdefGlyph].concat(font.stringToGlyphs(glyphs))
    
    const subsetFont = new opentype.Font({
        familyName: familyName,
        styleName: styleName,
        unitsPerEm: font.unitsPerEm,
        ascender: font.ascender,
        descender: font.descender,
        designer: font.getEnglishName("designer"),
        designerURL: font.getEnglishName("designerURL"),
        manufacturer: font.getEnglishName("manufacturer"),
        manufacturerURL: font.getEnglishName("manufacturerURL"),
        license: font.getEnglishName("license"),
        licenseURL: font.getEnglishName("licenseURL"),
        version: font.getEnglishName("version"),
        description: font.getEnglishName("description"),
        copyright: "This is a subset font of " + postScriptName + ". " + font.getEnglishName("copyright"),
        trademark: font.getEnglishName("trademark"),
        glyphs: subGlyphs
    })
 
    fs.writeFileSync(item.replace(".otf", ".subset.otf"),  new Float32Array(subsetFont.toArrayBuffer()))
})
```

I know up front (through translation files) exactly what text/glyphs I need to support so this subsetting seems to work OK. The added benefit is that this subsetting can be done for Western text too, reducing the file size for everybody.

**Comment by lojjic** [comment]
Closing this issue since it seems you've figured out a workable solution. :)

**Comment by lojjic** [comment]
FYI, as of version 0.48.0 there is now out of the box support for automatically loading CJK subset fonts to cover the characters in use.
