### ISSUE TITLE
Update PlaneGeometry

### ISSUE THREAD

**Issue by flaaudwls** [protectwise/troika#241]
I think there is no planeBufferGeometry in recent versions of ThreeJS.
When I use troika text, I am getting this warning saying 'THREE.PlaneBufferGeometry has been renamed to THREE.PlaneGeometry.'
Please update the dependency to remove this warning.
Thank you.

**Comment by lojjic** [comment]
Are you using the latest version 0.47? This should have already been fixed.

**Comment by flaaudwls** [comment]
Thank you for confirming that. I am using "troika-three-text": "^0.47.1".
Looks like Troika Text component of  react/three-drei needs to be updated.
