### ISSUE TITLE
BUG: renderer.info.autoReset = false; Cause troika-three-text not to appear

### ISSUE THREAD

**Issue by liorGameDev** [protectwise/troika#245]
I added the line:
`renderer.info.autoReset = false;`
In order to add a custom stats object, and it causes the text to disapear.
What is the reason for it?
Is there a way to make them both exist?

**Comment by lojjic** [comment]
I can't imagine why the renderer info stats would affect troika text rendering at all. Can you provide a demonstration showing the issue?

**Comment by lojjic** [comment]
I can't reproduce this locally.

**Comment by liorGameDev** [comment]
Pls try this CodeSandbox link:
https://codesandbox.io/s/kind-joliot-yljv3p?file=/src/BasicThreeDemo.js
If you will change line 12 in BasicThreeDemo.js to 
`  this.renderer.info.autoReset = true;`
You will be able to see the text, and if it is false you will not be able to see it.

**Comment by lojjic** [comment]
That's very interesting, thanks for the repro. Not sure why it didn't happen for me locally.

There seems to be an overall bug/quirk in Three where setting `info.autoReset=false` prevents `info.render.frame` from being incremented on each frame -- but that frame counter is actually used by several things to determine whether it needs to update internal state or not, so if it's not incremented certain things get stale. Something used by troika text must be one of those things.

As a workaround, you can try manually incrementing `info.render.frame`: https://codesandbox.io/s/gallant-browser-v1t3xn?file=/src/BasicThreeDemo.js:1872-1911

**Comment by liorGameDev** [comment]
Thanks for the answer!
