### ISSUE TITLE
Position seems to be changing before text label update

### ISSUE THREAD

**Issue by bryaan** [protectwise/troika#250]
I am noticing that when creating a label in one render frame and then updating its position and text label in another frame, that the old text label is in the new position before changing to the new label.  Can any maintainers see why this is happening?

The proper order should be:

1. Make label invisible.
2. Move label and update text.
3. Make visible.

It seems internally the text is not being made invisible.

**Comment by lojjic** [comment]
Text updates are asynchronous, meaning the change may not be complete until the next frame or later. If you call `.sync(callback)` and do the move/visible in that callback it should help. See the [docs section on async behavior](https://github.com/protectwise/troika/tree/main/packages/troika-three-text#handling-asynchronous-updates) too.

**Comment by bryaan** [comment]
Doing 

```
text.sync(() => {
    text.visible = true
})
```

does not update the visibility of the text.

**Comment by lojjic** [comment]
Can you provide a test case showing your full issue? It's hard to diagnose with isolated snippets.

**Comment by lojjic** [comment]
Closing for now, reopen if you can provide more info for diagnosing.
