### ISSUE TITLE
ReferenceError `_babel_runtime_helpers_esm_createClass__WEBPACK_IMPORTED_MODULE_12__ is not defined`

### ISSUE THREAD

**Issue by baptistebriel** [protectwise/troika#275]
Hi! First of all, thanks for this very helpful module. 

I am just getting this fresh error (haven't found any other tickets related, maybe #111 ?) with error `ReferenceError: _babel_runtime_helpers_esm_createClass__WEBPACK_IMPORTED_MODULE_12__ is not defined`

I am running the project with Vue / Nuxt 2, and seems like it's happening on first call of `text.sync()`.
Happens with both `0.48.0-unicode.3` and `0.48.0-unicode.1`.

<img width="1190" alt="Screenshot 2023-08-08 at 15 10 02" src="https://github.com/protectwise/troika/assets/2464663/35d4a909-8491-4c56-908b-9178e18c0e66">

Would you have an idea?

**Comment by baptistebriel** [comment]
Using `"troika-three-text": "^0.47.2"` seems to have removed the error.

**Comment by lojjic** [comment]
Should be fixed in 0.48.0
