### ISSUE TITLE
R3F: Ade font style is not working on some glyphs

### ISSUE THREAD

**Issue by AxiomeCG** [protectwise/troika#286]
Hello,

I wanted to use the Ade font and for some reason it is not rendering properly using the drei <Text/> component, that is wrapping troika-three-text I assume.

I wanted to know if there is anything to do about that ? Is it specific to the font itself ? 

Here is the code I tried so far.
```jsx
<>
  <Text font={"/Ade.ttf"} fontSize={12} position={[-10,5,-5]} color={"#222222"}>
              AAAAAA
  </Text>
  <Text font={"/Ade.ttf"} fontSize={12} position={[-10,5,-5]} fillOpacity={0} strokeColor={"#222222"} strokeWidth={0.175}>
              AAAAAA
              <meshBasicMaterial color={"#222222"} depthTest={false}/>
  </Text>
</>
```

Glyph generated in 2D in r3f: 
<img width="177" alt="image" src="https://github.com/protectwise/troika/assets/18304870/2ec17b9f-b70f-4823-988d-bdb86226a939">

List of glyph of the font : 

<img width="638" alt="image" src="https://github.com/protectwise/troika/assets/18304870/0dd3acb3-98c9-4ebf-954c-ea6a6892c49c">

Here is the font formats that I tried so far of the Ade font. 
[Ade-font.zip](https://github.com/protectwise/troika/files/13491681/Ade-font.zip)
You can also find it in : https://fontesk.com/ade-display-font/

**Comment by lojjic** [comment]
That font has some very thin line features which can be difficult for SDF-based rendering. You might see some improvement if you set a higher [`sdfGlyphSize`](https://protectwise.github.io/troika/troika-three-text/#sdfglyphsize).

**Comment by AxiomeCG** [comment]
Thank you for the tip, it makes it better but aliased with sdfGlyphSize=512
<img width="162" alt="image" src="https://github.com/protectwise/troika/assets/18304870/ab24fa24-2e7a-4dab-96d2-73d3f16f93b7">

I happen to have increase the weight of the font in a font editor to see if it would be better, and it is nicer, but I would like if possible to be able to use the lib at its maximum potential for all kind of fonts so it is nice to know there is some adjustments that can be done !

**Comment by lojjic** [comment]
Yeah that A has a stray point way out at `-3914,-1812`. This needs to be fixed in the font.

<img width="776" alt="image" src="https://github.com/protectwise/troika/assets/138124/99eb5716-1f03-47e5-9958-10cf2a277a12">

**Comment by AxiomeCG** [comment]
Thank you for your guidance, I guess I can close the issue where it is mostly about the font, more than the lib itself !
