### ISSUE TITLE
Text.sync can't update the mesh smoothly when I excute sync method quickly

### ISSUE THREAD

**Issue by HawtinZeng** [protectwise/troika#291]
[screen-capture.webm](https://github.com/protectwise/troika/assets/73981739/6cce9bd3-3f9f-4732-bc4f-77ea2dda56ac)
I want to redraw the text in real-time, what should I do, any suggestions?

**Comment by lojjic** [comment]
I don't know why you're seeing it go blank briefly. Are you destroying and recreating the Text instance perhaps? I don't know if I can help without seeing your code.

**Comment by HawtinZeng** [comment]
> I don't know why you're seeing it go blank briefly. Are you destroying and recreating the Text instance perhaps? I don't know if I can help without seeing your code.

Yes, I create Text Mesh and dispose it , then recreate a Text Mesh.
I find that maybe it needs some time to recreate Text Mesh because this process is executed in a web worker? When I recreate a normal Mesh(such as PlaneGeometry mesh), it is very smooth.
And I realized my requirement with translating the Text instead of recreating a new Text Mesh, that's smooth.

**Comment by lojjic** [comment]
Ah, that makes sense then. Definitely reuse a single instance when possible. :)
