### ISSUE TITLE
About fonts CDN

### ISSUE THREAD

**Issue by HawtinZeng** [protectwise/troika#292]
Normally, I have to pass font as the font CDN, but I wanna use a common font installed in clients' system, how can I avoid load font file?

**Comment by HawtinZeng** [comment]
![image](https://github.com/protectwise/troika/assets/73981739/3f53e4bd-69c7-48b1-b73d-8ee8ea1e973d)
I wanna to forcely reset the default font loaded by default CDN, but I can't access uTroikaSDFTexture.value(the assigned texture) in sync callback : (

**Comment by lojjic** [comment]
This won't work as you expect. We need access to the full font file, and the browser does not allow access to fonts installed on the system. If you need to use system fonts, then you'll need to use a different tool, like a CanvasTexture.

**Comment by HawtinZeng** [comment]
> This won't work as you expect. We need access to the full font file, and the browser does not allow access to fonts installed on the system. If you need to use system fonts, then you'll need to use a different tool, like a CanvasTexture.

Ok, thanks for your response : )
