### ISSUE TITLE
Emoji and Unicode support

### ISSUE THREAD

**Issue by nicholasvperry** [protectwise/troika#299]
Should be allowed to use emojis and Unicode.

**Comment by lojjic** [comment]
What's not working for you specifically?

**Comment by lojjic** [comment]
It looks like Threlte is a couple versions behind; the current version should handle this for you, although the emojis will be monochrome.

**Comment by ssadler** [comment]
Would it be possible to render image emoji by passing the caret positions as well as a texture atlas with all the emoji into the shader?

I guess `_textRenderInfo.caretPositions` will correspond to the `position` data in the fragment shader?
