### ISSUE TITLE
troika-three-text: The color space of text color is incorrect with Three.js r154+

### ISSUE THREAD

**Issue by asyncore** [protectwise/troika#324]
Color space is applied to a text color using custom shaders in `upgradeShaders()` ([troika-three-utils/src/DerivedMaterial.js#L306](https://github.com/protectwise/troika/blob/d23f360c4316fa782d351151062ea3b0c2629ca1/packages/troika-three-utils/src/DerivedMaterial.js#L306)) through injecting custom shader code into the `encodings_fragment` shader. The shader has been renamed to `colorspace_fragment` in https://github.com/mrdoob/three.js/pull/26206 since Three 154. So, the `troika-three-text` package doesn't fully support Three.js r154+.

The fix would be to include `colorspace` in the RegEx pattern in [troika-three-utils/src/DerivedMaterial.js#L306](https://github.com/protectwise/troika/blob/d23f360c4316fa782d351151062ea3b0c2629ca1/packages/troika-three-utils/src/DerivedMaterial.js#L306) as follows:

```
fragmentShader = fragmentShader.replace(
/^[ \\t]*#include <((?:tonemapping|encodings|colorspace|fog|premultiplied_alpha|dithering)_fragment)>/gm,
'\\n//!BEGIN_POST_CHUNK $1\\n$&\\n//!END_POST_CHUNK\\n')
```

I can make a PR for this fix.

**Comment by lojjic** [comment]
Great investigative work! I'll accept that PR.
