### ISSUE TITLE
Active color for label for edges is not working without the animated option

### ISSUE THREAD

**Issue by Flowtter** [protectwise/troika#329]
Hi,

for `"reagraph": "4.19.3"`,
the configuration:
```
        label: {
            stroke : "#ff0000",
            color : "#00ff00",
            activeColor : "#0000ff",
        },
```
Is not making the color of the active label change, without the animated option set to True

Thank you

**Comment by lojjic** [comment]
Did you file this in the wrong project?

**Comment by lojjic** [comment]
Closing, this seems like a reagraph thing. Reopen with more details if I'm misunderstanding.
