### ISSUE TITLE
troika-3d-text: letterSpacing is applied before first character of each line

### ISSUE THREAD

**Issue by feiss** [protectwise/troika#33]
Example with **letterSpacing** of 2.55. Text is `"Lorem\nIPSUM\nDolor\nsit amet"`.

 `alignX` is 'left', so all lines should be perfectly aligned to the first L.

<img width="462" alt="Screenshot 2020-03-28 at 01 23 23" src="https://user-images.githubusercontent.com/359872/77810043-befcdc00-7092-11ea-8879-eaa1f05ab69f.png">

**Comment by lojjic** [comment]
Thanks for the report! Fixed in 61cb4f8.
