### ISSUE TITLE
BatchedText: make _mat4Texture max texture size as an option

### ISSUE THREAD

**Issue by upisfree** [protectwise/troika#339]
Hello. Thanks for Troika; it's awesome!

I am trying to optimize my text rendering. I have a lot of small texts with the same material and font parameters, so I tried to use BatchedText. When I had ~400 text elements, I had this problem with rendering:
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/81d915e4-e0a0-414c-941c-ed3d8d8371b8">

Should be like this:
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/72ed3404-4afa-411b-bf9b-d69208e6b073">

So, I found the reason is `BatchedText._mat4Texture` max width is hardcoded as **1024px**, no matter how many Text items I actually have. When I increased max texture width, the problem was fixed.

I want to make a pull request that fixes it, but what option should I make in the BatchedMesh constructor: max texture width or max members count (and calculate max texture width depending on that)?
And second question, should we really use power-of-two texture? It seems like WebGL 1 restriction and now WebGL 2 is widely available.

Thanks!

**Comment by lojjic** [comment]
The texture *width* is a fixed max value but its height should be dynamically resized to fit your number of items. Perhaps there's something wrong with that math, or with how the values are read out of the texture in the shader?

Thanks for trying BatchedText out in its early stages, by the way. This helps shake out issues :)

**Comment by lojjic** [comment]
Found the bug, it was in the shader. Can you try out that PR I opened and verify it fixes your issue?

**Comment by upisfree** [comment]
Confirming, it fixes the issue without changing width of the texture. Thank you!
