### ISSUE TITLE
troika-3d-text: lineHeight adds a space before first line

### ISSUE THREAD

**Issue by feiss** [protectwise/troika#35]
all these multiline texts have the same Y, but with different lineHeights. Notice how the first line starts lower as we increase the lineHeight (ignore the red frame):

<img width="693" alt="Screenshot 2020-04-02 at 19 58 43" src="https://user-images.githubusercontent.com/359872/78282326-5e4f2280-751c-11ea-841a-bb6477b5008f.png">

**Comment by lojjic** [comment]
Hmm, I think that's the expected behavior actually, since I'm trying to generally match what CSS does:

![image](https://user-images.githubusercontent.com/138124/78283006-671f0480-74da-11ea-9255-3ecf0b3ad1d0.png)

I take it that's not how Blender handles its line heights?

**Comment by feiss** [comment]
Haha, you got me! 

Leave it like that, makes sense to follow CDs behavior
