### ISSUE TITLE
Promote standalone TextMesh to its own package

### ISSUE THREAD

**Issue by lojjic** [protectwise/troika#47]
Now that the standalone TextMesh is being used by several third party ThreeJS frameworks and projects, the fact that those users have to explicitly import from a secondary file in the dist directory rather than just the package name feels ... wrong.

I'm proposing to add a new package that will hold all the code currently used by the standalone build, and the existing troika-3d-text will reference that and just add the extra stuff related to usage in the Troika framework. This will be a breaking change for projects using it, but that will be the case at some point regardless so sooner is better IMO.

Possible names for the new package:
- troika-three-text
- troika-three-textmesh
- ...?

I'm open to renaming any exports as well ... TextMesh -> Text perhaps?

**Comment by drcmda** [comment]
sounds fantastic!

**Comment by lojjic** [comment]
Done, as of v 0.29.0. We now have a `troika-three-text` package, with a `Text` export.

@drcmda FYI ^ for when you do your next update within `drei`.
