### ISSUE TITLE
how to position text, f.i upper/left?

### ISSUE THREAD

**Issue by drcmda** [protectwise/troika#49]
demo: https://codesandbox.io/s/r3f-troika-text-l40jo?file=/src/index.js

it seems to behave very strange when i anchor it left/op, then move it via position to minus half the viewports width/height so that it should be exactly at the upper left border.

it makes no sense to me, but this setting makes the text disappear completely:

```jsx
<Text position={[-viewport.width / 2, 0, 0]}
```

while adding a tiny digit shows it again:

```jsx
<Text position={[-viewport.width / 2.1, 0, 0]}
```

same happens at the top, the offsets that are 100% correct but a clean width / 2 makes the text go away.

it looks to me like something in the shader is clipping it incorrectly.

**Comment by drcmda** [comment]
ps, at this point the Text component is just

```jsx
from 'troika-3d-text/dist/textmesh-standalone.umd'

export const Text = forwardRef(({ children, ...props }: Props, ref) => {
  return <textMeshImpl ref={ref} text={children} {...props} />
})
```

**Comment by lojjic** [comment]
Ooh this is a fun one! 😆 Took me a while to see what's going on. 

Basically `sync()` isn't getting called when the initial origin is offscreen. The geometry's initial bounding sphere is a zero-radius sphere at local [0,0,0], so if the mesh's origin is initially outside the camera's frustum then ThreeJS will cull it out of the render pass. That prevents `onBeforeRender` from being called, so it doesn't hit the fallback `sync()` call there, and the text never renders.

Two possible solutions I can think of off the bat:
1. You could add a call to `sync()` in a useEffect hook or similar
2. I could disable frustum culling for the TextMesh prior to the first sync call, by
  a. giving it an infinite boundingSphere, or
  b. something tricky with a `frustumCulled` getter

**Comment by drcmda** [comment]
number 1 worked, merged your material fix and that had sync already, thanks!

**Comment by lojjic** [comment]
Cool! I may try to do the second workaround anyway, as a backup.
