### ISSUE TITLE
Errors loading fonts

### ISSUE THREAD

**Issue by ryanking1809** [protectwise/troika#50]
There seems to be an issue loading fonts?
https://codesandbox.io/s/threejs-bare-example-w00pp?file=/index.js

I was thinking maybe it was codesandbox but the react-three-fiber example works fine. I wonder what is happening differently 🤔

**Comment by lojjic** [comment]
Codesandbox does have some strange quirks. One of them I've found is that it doesn't like the .esm.js file, but if you import from textmesh-standalone.umd.js it works fine. No idea why. 🤷  That and bumping up the font size seems to fix your example.

**Comment by ryanking1809** [comment]
Awesome that did the trick! It's so much better than my previous solution, it looks great on windows and it's so much easier not having to generate the textures yourself. Thanks for this!
