### ISSUE TITLE
[request] number of segments

### ISSUE THREAD

**Issue by drcmda** [protectwise/troika#52]
I would like to configure the number of segments of the surface plane, similar to

```jsx
new PlaneBufferGeometry(1, 1, 32, 32) // 32 x 32 segments/vertices
```

so that we can warp the surface like so: https://codesandbox.io/s/r3f-drei-meshwobblematerial-g5373

currently if i pass that wobbly material to troika it behaves very rigid: https://codesandbox.io/s/r3f-drei-meshwobblematerial-rwmrx i guess that's because the surface behaves like a plane with 1x1 segments.

can this be done somehow?

**Comment by lojjic** [comment]
Cool idea! Should be pretty easy.

**Comment by lojjic** [comment]
Quick-n-dirty prototype: ![Kapture 2020-06-05 at 10 29 43](https://user-images.githubusercontent.com/138124/83901255-b0c4df00-a717-11ea-8c5a-f5e19780bff6.gif)

I'll clean it up and publish after real work. ;)

**Comment by drcmda** [comment]
yay! im making a poor mans awwwards starter kit with this one :-P

**Comment by drcmda** [comment]
is this in 0.27.1? glyphGeometryDetail doesn't seem to have any effect ...

**Comment by lojjic** [comment]
Sorry not published yet, just in master

**Comment by drcmda** [comment]
any idea when its going up? :-D

**Comment by lojjic** [comment]
v0.28.0 just published.
