### ISSUE TITLE
Raycast original TextMesh

### ISSUE THREAD

**Issue by danko-master** [protectwise/troika#62]
Hi! I created a  `group = new THREE.Group()`,  also `textMesh = new TextMesh() ` and added it to the group - `group.add(textMesh)`. When I called raycast I got a new object (in source `raycastMesh =  new Mesh`). But I need an original object with parent. How do I do that?

**Comment by lojjic** [comment]
Thanks for pointing this out. Is it just the `object` property on each intersection object that is incorrect?

**Comment by danko-master** [comment]
In my project I search parent for each intersection object. When ray is intersect the TextMesh my project crashed, because raycaster return me clone of TextMesh (not original object with reference for parent group).

**Comment by lojjic** [comment]
Yes I understand, I'm asking for specifics so I make sure I fix the issue correctly. What exactly does "raycaster return me clone of TextMesh" mean? Is it the `object` property on the objects in the intersects array you pass to raycast()?

**Comment by lojjic** [comment]
OK, assuming it's just the `intersection.object` property you're talking about, I've just published v 0.28.1 which should fix that for you. Please reopen with additional detail if this doesn't work for you. Thanks!
