### ISSUE TITLE
troika 3d text: Support for Special Characters?

### ISSUE THREAD

**Issue by natarius** [protectwise/troika#66]
I noticed special characters like Omega don't seem to be supported?

Or am I doing something wrong?

I am using the default font and not loading a custom one

Roboto (default font) definitely supports it: https://fonts.google.com/specimen/Roboto?preview.text=%E2%84%A6&preview.text_type=custom

<img width="241" alt="Screen Shot 2020-06-30 at 3 57 45 PM" src="https://user-images.githubusercontent.com/607331/86185246-bf21d300-baea-11ea-9297-c37ab260ffc5.png">

**Comment by natarius** [comment]
posted in wrong repo

**Comment by natarius** [comment]
no, its the right repo :)

**Comment by lojjic** [comment]
Definitely the right repo. 😄

Any character should work, but the font file has to include that glyph. It doesn't look like the default Roboto woff file contains that one (it's a basic Latin charset I believe), so you'll want to use one that does.

**Comment by natarius** [comment]
Do you happen to know how to get a url for Roboto that includes the full charset?

the embed url google fonts provides doesn't seem to work: https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap

and when you look into the return it seems that additional charsets come as additional woff files...is there a way to provide the .font method multiple fonts?

**Comment by lojjic** [comment]
I'm not sure if there's a way through Google Fonts to get a combined woff of multiple subsets. Possibly you could use the `text=` parameter to the css2 api to list all the characters you need including the omega? https://developers.google.com/fonts/docs/css2#optimizing_your_font_requests -- note that will give you .woff2 files by default, I sometimes spoof my browser user agent to look like IE10 to get .woff files from it.

There's also [this command line script](https://github.com/protectwise/troika/blob/978ef534442ec159353c8aa4c0ebe45ac21b4189/packages/troika-3d-text/find-google-font-url.js) which automates some of that fetching. It doesn't currently support that `text=abc` parameter but you could add it.

Also, see issue #13, which I think is probably the long-term solution for this.

**Comment by natarius** [comment]
found a site that can merge the different charsets into one woff file

https://google-webfonts-helper.herokuapp.com/fonts/roboto?subsets=greek,greek-ext,latin,latin-ext

**Comment by lojjic** [comment]
@natarius Wow that's a very helpful tool! Thanks for letting me know about it. I'll add a reference to that in the docs.
