### ISSUE TITLE
[troika-3d-text] Missing characters

### ISSUE THREAD

**Issue by Ocelyn** [protectwise/troika#69]
Hello, first of all, thank you for your amazing work!

I have a weird issue using troika 3d text.

If I init my Text() with a text with 3 characters length.
And then I change it for a longer text (let's say "hello") only "hel" will be displayed.

Do you have any idea where the problem could be from?

Thank you!

**Comment by arpu** [comment]
i had this problem too, but need to look how i resolved this

**Comment by arpu** [comment]
@Ocelyn  do you use threejs or aframe?

**Comment by Ocelyn** [comment]
@arpu Thank you for your reply! Threejs

**Comment by arpu** [comment]
ok, what i do is recreate the troika-text on change, but this looks more a bug @lojjic ?

**Comment by lojjic** [comment]
This definitely shouldn't happen, and I change text all the time with no issues. Can you provide a simple testcase that demonstrates the bug?

**Comment by lojjic** [comment]
Nevermind, I was able to reproduce the bug. I will fix ASAP.

**Comment by Ocelyn** [comment]
@lojjic Thank you so much!

**Comment by lojjic** [comment]
This bug is caused by an internal change in ThreeJS that they introduced in r117. I'm getting a workaround in place. In the meantime, using ThreeJS r116 should work for you.

**Comment by lojjic** [comment]
The underlying issue deserves more investigation, but I've got a workaround in place. Version 0.30.1 should fix it for you, please try it and reopen this if you still have issues. Thanks!

**Comment by arpu** [comment]
any chance for the aframe update?

**Comment by lojjic** [comment]
@arpu I just published aframe-troika-text 0.4.0

**Comment by arpu** [comment]
wau thx!

**Comment by lojjic** [comment]
Reopening... the workaround has surfaced another bug that causes pieces of text to disappear. I suspect it's due to disposing the geometry. https://github.com/react-spring/drei/issues/62
