### ISSUE TITLE
[Feature][troika-three-text] Text to Sprite

### ISSUE THREAD

**Issue by Momohanfeng** [protectwise/troika#71]
Hi sir, I want to know how to use the Text as THREE.Sprite,  because some function model need the text to keep size and keep looking at camera just like the Sprite's behavior.

I think this feature will be very useful.

**Comment by lojjic** [comment]
I've given this some thought and while I agree that having text face the camera and scale by distance is a useful feature, it probably shouldn't happen just within the text implementation. For instance if you're building UI or labels with a background plane behind the text, then you want that whole collection of objects to rotate and scale, not just the text.

I imagine this could be wrapped up nicely in a three `Group` with an onBeforeRender handler that adjusts the whole group's world matrix based on camera frustum on each frame. There may already be community packages out there that do this.
