### ISSUE TITLE
[Question] use local installed Font Glyphs

### ISSUE THREAD

**Issue by arpu** [protectwise/troika#81]
Hey,

try to get Japanese and Vietnam fonts ready for 3D,

first idea was to use different woff files for different Languages but this have huge file size.

would it be possible to use the local installed Glyps like Twitter is using it 

i found this in the chrome dev console 
![Bildschirmfoto von 2020-09-26 12-30-34](https://user-images.githubusercontent.com/14173/94338629-28cf5180-fff4-11ea-8d51-23d409da8897.png)

**Comment by lojjic** [comment]
That would be wonderful, but unfortunately there is no API for JavaScript to access data from locally installed fonts.

**Comment by arpu** [comment]
found this one https://web.dev/local-fonts/ 

looks like chrome has a dev flag for this
