### ISSUE TITLE
[3DText] Webxr flicker if Video is in Scene

### ISSUE THREAD

**Issue by arpu** [protectwise/troika#86]
Hello,

after some testing i found the Text flicker if a Video is in View any idea how i could/should debug this? 

hope the Video shows what i mean (Oculus quest 2) 
https://youtu.be/bOneEEStYn8

**Comment by lojjic** [comment]
That's very strange, I can't think of a reason off the top of my head. Is this somewhere I can access it? I own a quest 2.

**Comment by arpu** [comment]
https://vrland.io/ best enter the Lobby and enter the Cinema on the right controller press B Button to show the Menue

**Comment by lojjic** [comment]
Very strange indeed. I notice that the flicker isn't always consistent, it seems to depend somewhat on the angle of view. I can get it to stop flickering while the video is in view by standing/sitting/moving closer to the text, and I can get it to flicker at some angles when the video is out of view (though maybe not fully frustum-culled). It behaves _sort of_ like z-fighting in that regard, but I doubt it's strictly that.

I also notice that when the text starts flickering, the overall quality of the UI panel goes down as well; the edges of the UI's background planes get all jagged. I wonder if the Quest is knocking down the viewbuffer resolution or swapping some rendering mode when the video is in scene? Something trying to adapt rendering quality to keep frame rate up?

**Comment by arpu** [comment]
Hey, thx a lot to looking at this! i will do some moe testing with a more simple example today, and maybe @Artyom17 has some Idea?

**Comment by arpu** [comment]
done more testing on test looks like its with any THREE MeshStandardMaterial but not with the BasicMaterial 

see the Buttons 
![Bildschirmfoto von 2021-05-24 19-38-09](https://user-images.githubusercontent.com/14173/119386396-c421df00-bcc7-11eb-9101-00bc69195b27.png)
![Bildschirmfoto von 2021-05-24 19-37-51](https://user-images.githubusercontent.com/14173/119386400-c4ba7580-bcc7-11eb-9d6e-c00763fc82c3.png)

@cabanier any Idea?

**Comment by arpu** [comment]
@lojjic  looks like the Text is not Flicker anymore, maybe  i could fix this in my rounded boy shader? 

its simple 
```
this.boxMat.onBeforeCompile = ( shader ) => {

			shader.uniforms.boxSize = settings.size;
			shader.uniforms.radius = settings.radius;

			shader.vertexShader =
				`
            uniform vec3 boxSize;
            uniform float radius;
            ` + shader.vertexShader;

			shader.vertexShader = shader.vertexShader.replace(
				`#include <begin_vertex>`,
				`#include <begin_vertex>
              
          
          
              vec3 signs = sign(position);
              vec3 box = boxSize - vec3(radius);
              box = vec3(max(0.0, box.x), max(0.0, box.y), max(0.0, box.z));
              vec3 p = signs * box;
          
              transformed = signs * box + normalize(position) * radius;
			  // re-compute normals for correct shadows and reflections
			  objectNormal = all(equal(p, transformed)) ? normal : normalize(position); 
			 transformedNormal = normalize(normalMatrix * objectNormal);
			  vNormal = transformedNormal;
			  
		
		
              `,
			);

		};
```

**Comment by cabanier** [comment]
I don't see any flickering on my end.
What version is your browser and your OS? Also, can you post a movie capture?

**Comment by arpu** [comment]
@ca

> I don't see any flickering on my end.
> What version is your browser and your OS? Also, can you post a movie capture?

 forget to add, this only happens in webxr on oculus quest ( will try to record a video) 
chrome and quest version: 
![191355203_10223762191150105_1229511222235514645_n](https://user-images.githubusercontent.com/14173/119391655-e9feb200-bcce-11eb-9e7c-93c9e80b2278.jpg)

**Comment by cabanier** [comment]
You have the latest. Is it Quest 1 or 2?

**Comment by arpu** [comment]
Quest 2 OS: Android 10 QUest 2 Build QQ3A.200805.001

**Comment by arpu** [comment]
will do some more testing with a simple setup

**Comment by arpu** [comment]
happy i can tell  this is fixed with 

```
const material = new THREE.MeshBasicMaterial( { map: texture } );
material.flatShading = true;
material.transparent = true;
```

sorry @cabanier for the noise! 

still not sure why this is needed but works for now
